USE [Orocom]

 ALTER TABLE Usuario
  add constraint FK_UsuPersona
  foreign key (Persona)
  references PersonaMast (Persona);

SELECT * FROM PersonaMast
SELECT * FROM Usuario
SELECT * FROM SCI_TAREAS
SELECT * FROM SCI_ALERTAS
SELECT * FROM SCI_ACCIONES

SELECT * FROM TK_Ticket
SELECT * FROM TK_Responsable
SELECT * FROM TK_Usuario
SELECT * FROM TK_Estado
--SELECT * FROM TK_Responsable
--ComercialContent


--CREATE VIEW [dbo].[VIEW_Usuario]
--AS
--SELECT P.Persona,p.Documento ,p.TipoDocumento,p.NombreCompleto ,p.ApellidoPaterno ,p.ApellidoMaterno , 'Interno' as TipoUsuario,
-- U.*, case U.Activo when 1 then 'Activo' else 'Inactivo' end DesEstado
--FROM TK_Usuario U WITH(NOLOCK)
--INNER join PersonaMast p WITH(NOLOCK) on p.Persona = U.Id

--GO

GO
/****** Object:  Table [dbo].[Estado]    Script Date: 17/04/2024 23:07:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TK_Estado](
	[Id] [int] NOT NULL,
	[Nombre] [varchar](20) NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_TK_Estado] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Responsable]    Script Date: 17/04/2024 23:08:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TK_Responsable](
	[Id] [int] NOT NULL,
	[Nombres] [varchar](50) NOT NULL,
	[Apellidos] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Cargo] [varchar](100) NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_TK_Responsable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Usuario]    Script Date: 17/04/2024 23:08:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TK_Usuario](
	[Id] [int] NOT NULL,
	[Nombres] [varchar](50) NOT NULL,
	[Apellidos] [varchar](50) NOT NULL,
	[Telefono] [varchar](20) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_TK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Ticket]    Script Date: 17/04/2024 23:08:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TK_Ticket](
	[Id] [int] NOT NULL,
	[FechaGeneracion] [datetime] NOT NULL,
	[Descripcion] [varchar](max) NOT NULL,
	[Solucion] [varchar](max)  NULL,
	[IdEstado] [int] NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[IdResponsable] [int] NOT NULL,
 CONSTRAINT [PK_TK_Ticket] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TK_Ticket]  WITH CHECK ADD  CONSTRAINT [FK_TK_Ticket_IdEstado] FOREIGN KEY([IdEstado])
REFERENCES [dbo].[TK_Estado] ([Id])
GO
ALTER TABLE [dbo].[TK_Ticket]  WITH CHECK ADD  CONSTRAINT [FK_TK_Ticket_IdResponsable] FOREIGN KEY([IdResponsable])
REFERENCES [dbo].[TK_Responsable] ([Id])
GO
ALTER TABLE [dbo].[TK_Ticket]  WITH CHECK ADD  CONSTRAINT [FK_TK_Ticket_IdUsuario] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[TK_Usuario] ([Id])
GO



CREATE TABLE SCI_TAREAS
( 
	ID_TAREA             int  NOT NULL ,
	NROREQUERIMIENTO     varchar(20)  NULL ,
	TIPO                 int  NULL ,
	TAREA                varchar(100)  NULL ,	
	ID_SOLICITANTE       int  NULL ,
	ID_RESPONSABLE       int  NULL ,
	ID_ALTERNO           int  NULL ,	
	ID_INVOLUCRADO       int  NULL ,
	IDAREA               int  NULL ,
	FECHAREGISTRO        datetime  NULL ,
	FECHAINIPLAZO        datetime  NULL ,
	FECHAFINPLAZO        datetime  NULL ,	
	PRECIO               money  NULL ,
	OBSERVACION          varchar(200)  NULL ,
	ESTADO               int  NULL ,
	USUARIOCREACION      varchar(20)  NULL ,
	USUARIOMODIFICACION  varchar(20)  NULL ,
	FECHACREACION        datetime  NULL ,
	FECHAMODIFICACION    datetime  NULL ,
	IPCREACION			varchar(20)  NULL ,
	IPMODIFICACION 		varchar(20)  NULL ,
	 PRIMARY KEY  CLUSTERED (ID_TAREA ASC),
	 FOREIGN KEY (ID_SOLICITANTE) REFERENCES TK_Usuario(Id),
	 FOREIGN KEY (ID_RESPONSABLE) REFERENCES TK_Usuario(Id),
	 FOREIGN KEY (ID_ALTERNO) REFERENCES TK_Usuario(Id),
	 FOREIGN KEY (ID_INVOLUCRADO) REFERENCES TK_Usuario(Id)
)
go

CREATE TABLE SCI_ACCIONES
( 
	ID_ACCION            int  NOT NULL ,	
	ID_TAREA             int  NOT NULL ,	
	ID_RESPONSABLE       int  NULL ,
	DESCRIPCION          varchar(200)  NULL ,
	FECHA                datetime  NULL ,	
	OBSERVACION          varchar(200)  NULL ,
	ESTADO               int  NULL ,
	USUARIOCREACION      varchar(20)  NULL ,
	USUARIOMODIFICACION  varchar(20)  NULL ,
	FECHACREACION        datetime  NULL ,
	FECHAMODIFICACION    datetime  NULL ,
	IPCREACION			varchar(20)  NULL ,
	IPMODIFICACION 		varchar(20)  NULL ,
	 PRIMARY KEY  CLUSTERED (ID_TAREA ASC,ID_ACCION ASC),
	 FOREIGN KEY (ID_RESPONSABLE) REFERENCES TK_Usuario(Id),
	 FOREIGN KEY (ID_TAREA) REFERENCES SCI_TAREAS(ID_TAREA)
)
go

CREATE TABLE SCI_ALERTAS
( 
	ID                   int  NOT NULL ,	
	IDRELACIONADO        int  NOT NULL ,
	TIPOALERTA           int  NULL ,
	PROCESO              int  NULL ,
	CODIGO               varchar(20)  NULL ,
	IDPERSONA            int  NULL ,
	ESTADO               int  NULL ,	
	USUARIOCREACION      varchar(20)  NULL ,
	FECHACREACION        datetime  NULL ,
	IPCREACION			varchar(20)  NULL ,
	USUARIOMODIFICACION  varchar(20)  NULL ,
	FECHAMODIFICACION    datetime  NULL ,
	IPMODIFICACION 		varchar(20)  NULL ,
	 PRIMARY KEY  CLUSTERED (IDRELACIONADO, ID ASC),
	 FOREIGN KEY (IDPERSONA) REFERENCES TK_Usuario(Id)
)
go

--ALTER PROC [dbo].[SCI_ListarUsuario]
--@IDUSUARIO			int =null,
--@TIPOUSUARIO    	int =null,
--@USUARIO			varchar(25)=null,
--@NOMBRES			varchar(80)=null,
--@DOCUMENTO		    varchar(25)=null,
--@ESTADO	     		int=null
--as
--BEGIN
--select P.IDPERSONA,D.NOMBRE DESTIPOUSUARIO,p.NOMBRECOMPLETO ,p.APEPATERNO ,p.APEMATERNO ,p.NOMBRE , p.DOCUMENTO ,p.TIPODOCUMENTO,
--p.EMAIL , U.*, case U.Activo when 1 then 'Activo' else 'Inactivo' end DesEstado
--from TK_Usuario U WITH(NOLOCK)
--LEFT join  CM_CO_TablaMaestroDetalle D  WITH(NOLOCK) ON D.IDMAESTRO=5 AND   U.TIPOUSUARIO=D.CODIGO 
--INNER join PersonaMast p WITH(NOLOCK) on p.IDPERSONA = U.IDUSUARIO
--	WHERE  
--		(@IDUSUARIO = 0	or @IDUSUARIO is null	or U.IDUSUARIO = @IDUSUARIO )
--	and (@TIPOUSUARIO = 0 or @TIPOUSUARIO is null	or U.TIPOUSUARIO=@TIPOUSUARIO)
--	and (@USUARIO is null					or U.USUARIO like '%'+@USUARIO+'%')
--	and (@NOMBRES is null					or P.NOMBRECOMPLETO like '%'+@NOMBRES+'%')
--	and (@DOCUMENTO is null					or P.DOCUMENTO like '%'+@DOCUMENTO+'%')
--	and (@estado = 0 or @estado is null			or U.Estado=@estado)
--END
--GO

--ALTER PROCEDURE [dbo].[SCI_ListarTarea] 
--@IDTAREA		 	int =null,
--@IDSOLICITANTE		int =null,
--@IDRESPONSABLE		int =null,
--@IDALTERNO			int =null,
--@TIPO				int =null,
--@IDINVOLUCRADO		int =null,
--@IDAREA				int =null,
--@NROREQUERIMIENTO	varchar(25)=null,
--@TAREA				varchar(100)=null,
--@ESTADO				int=null,
--@FechaInicio		DATETIME =null,
--@FechaFinal			DATETIME=null 
--AS
--BEGIN

--	SELECT B.NOMBRECOMPLETO SOLICITANTE, C.NOMBRECOMPLETO RESPONSABLE,D.NOMBRECOMPLETO ALTERNO,G.NOMBRECOMPLETO INVOLUCRADO,
--	B.EMAIL EMAILSOLICITANTE, C.EMAIL EMAILRESPONSABLE,D.EMAIL EMAILALTERNO,G.EMAIL EMAILINVOLUCRADO,
--	E.NOMBRE TIPOREQUERIMIENTO, F.NOMBRE DESESTADO,F.DESCRIPCION COLORESTADO, H.NOMBRE AREA,CONVERT(VARCHAR,a.FECHAREGISTRO,103) FECREGISTRO,
--	CONVERT(VARCHAR,a.FECHAINIPLAZO,103) FECINIPLAZO, CONVERT(VARCHAR,a.FECHAFINPLAZO,103) FECFINPLAZO ,  A.* 
--	FROM SCI_TAREAS A WITH(NOLOCK)  
--	LEFT JOIN SCI_PERSONA B WITH(NOLOCK) ON  B.IDPERSONA=A.ID_SOLICITANTE
--	LEFT JOIN SCI_MAESTRODETALLE E WITH(NOLOCK) ON  E.CODIGO=A.TIPO AND E.IDMAESTRO=21
--	LEFT JOIN SCI_MAESTRODETALLE F WITH(NOLOCK) ON  F.CODIGO=A.ESTADO AND F.IDMAESTRO=22
--	LEFT JOIN SCI_PERSONA C WITH(NOLOCK) ON  C.IDPERSONA=A.ID_RESPONSABLE
--	LEFT JOIN SCI_PERSONA D WITH(NOLOCK) ON  D.IDPERSONA=A.ID_ALTERNO
--	LEFT JOIN SCI_PERSONA G WITH(NOLOCK) ON  G.IDPERSONA=A.ID_INVOLUCRADO
--	LEFT JOIN SCI_MAESTRODETALLE H WITH(NOLOCK) ON  H.CODIGO=A.IDAREA AND H.IDMAESTRO=24
--	WHERE  
--		(@IDTAREA = 0	or @IDTAREA is null					or A.ID_TAREA = @IDTAREA )
--	and (@IDSOLICITANTE = 0 or @IDSOLICITANTE is null		or A.ID_SOLICITANTE=@IDSOLICITANTE)
--	and (@TIPO = 0 or @TIPO is null							or A.TIPO=@TIPO)
--	and (@IDRESPONSABLE = 0 or @IDRESPONSABLE is null		or A.ID_RESPONSABLE=@IDRESPONSABLE)
--	and (@IDALTERNO = 0 or @IDALTERNO is null				or A.ID_ALTERNO=@IDALTERNO)
--	and (@IDINVOLUCRADO = 0 or @IDINVOLUCRADO is null		or A.ID_INVOLUCRADO=@IDINVOLUCRADO)
--	and (@IDAREA = 0 or @IDAREA is null						or A.IDAREA=@IDAREA)
--	and (@NROREQUERIMIENTO is null							or A.NROREQUERIMIENTO like '%'+@NROREQUERIMIENTO+'%')
--	and (@TAREA is null										or A.TAREA like '%'+@TAREA+'%')
--	and (@ESTADO = 0 or @ESTADO is null						or A.ESTADO=@ESTADO)
--	AND	(@FechaInicio IS NULL OR  @FechaFinal IS NULL OR convert(date, A.FECHAREGISTRO, 103) between convert(date, @FechaInicio, 103) and convert(date, @FechaFinal, 103))

--END
--GO
--ALTER PROCEDURE [dbo].[SCI_ListarTareaAsignadas] 
--@IDTAREA		 	int =null,
--@IDSOLICITANTE		int =null,
--@IDRESPONSABLE		int =null,
--@IDALTERNO			int =null,
--@TIPO				int =null,
--@IDINVOLUCRADO		int =null,
--@IDAREA				int =null,
--@NROREQUERIMIENTO	varchar(25)=null,
--@TAREA				varchar(100)=null,
--@ESTADO				int=null,
--@FechaInicio		DATETIME =null,
--@FechaFinal			DATETIME=null 
--AS
--BEGIN

--	SELECT B.NOMBRECOMPLETO SOLICITANTE, C.NOMBRECOMPLETO RESPONSABLE,D.NOMBRECOMPLETO ALTERNO,G.NOMBRECOMPLETO INVOLUCRADO,
--	B.EMAIL EMAILSOLICITANTE, C.EMAIL EMAILRESPONSABLE,D.EMAIL EMAILALTERNO,G.EMAIL EMAILINVOLUCRADO,
--	E.NOMBRE TIPOREQUERIMIENTO, F.NOMBRE DESESTADO,F.DESCRIPCION COLORESTADO, H.NOMBRE AREA,CONVERT(VARCHAR,a.FECHAREGISTRO,103) FECREGISTRO,
--	CONVERT(VARCHAR,a.FECHAINIPLAZO,103) FECINIPLAZO, CONVERT(VARCHAR,a.FECHAFINPLAZO,103) FECFINPLAZO ,  A.* 
--	FROM SCI_TAREAS A WITH(NOLOCK)  
--	INNER JOIN SCI_ALERTAS I WITH(NOLOCK) ON  I.IDRELACIONADO=A.ID_TAREA  AND I.TIPOALERTA=1
--	LEFT JOIN SCI_PERSONA B WITH(NOLOCK) ON  B.IDPERSONA=A.ID_SOLICITANTE
--	LEFT JOIN SCI_MAESTRODETALLE E WITH(NOLOCK) ON  E.CODIGO=A.TIPO AND E.IDMAESTRO=21
--	LEFT JOIN SCI_MAESTRODETALLE F WITH(NOLOCK) ON  F.CODIGO=A.ESTADO AND F.IDMAESTRO=22
--	LEFT JOIN SCI_PERSONA C WITH(NOLOCK) ON  C.IDPERSONA=A.ID_RESPONSABLE
--	LEFT JOIN SCI_PERSONA D WITH(NOLOCK) ON  D.IDPERSONA=A.ID_ALTERNO
--	LEFT JOIN SCI_PERSONA G WITH(NOLOCK) ON  G.IDPERSONA=A.ID_INVOLUCRADO
--	LEFT JOIN SCI_MAESTRODETALLE H WITH(NOLOCK) ON  H.CODIGO=A.IDAREA AND H.IDMAESTRO=24
--	WHERE  
--		(@IDTAREA = 0	or @IDTAREA is null					or A.ID_TAREA = @IDTAREA )
----	and (@IDSOLICITANTE = 0 or @IDSOLICITANTE is null		or I.IDPERSONA=@IDSOLICITANTE)
--	and (@TIPO = 0 or @TIPO is null							or A.TIPO=@TIPO)
--	and (@IDRESPONSABLE = 0 or @IDRESPONSABLE is null		or I.IDPERSONA=@IDRESPONSABLE)
----	and (@IDALTERNO = 0 or @IDALTERNO is null				or I.IDPERSONA=@IDALTERNO)
----	and (@IDINVOLUCRADO = 0 or @IDINVOLUCRADO is null		or I.IDPERSONA=@IDINVOLUCRADO)
--	and (@IDAREA = 0 or @IDAREA is null						or A.IDAREA=@IDAREA)
--	and (@NROREQUERIMIENTO is null							or A.NROREQUERIMIENTO like '%'+@NROREQUERIMIENTO+'%')
--	and (@TAREA is null										or A.TAREA like '%'+@TAREA+'%')
--	and (@ESTADO = 0 or @ESTADO is null						or A.ESTADO=@ESTADO)
--	AND	(@FechaInicio IS NULL OR  @FechaFinal IS NULL OR convert(date, A.FECHAREGISTRO, 103) between convert(date, @FechaInicio, 103) and convert(date, @FechaFinal, 103))

--END

--GO

--ALTER PROCEDURE [dbo].[SCI_ListarAccion] 
--@IDTAREA			int =null,
--@IDACCION			int =null,
--@IDRESPONSABLE		int =null,
--@ESTADO				int =null
--AS
--BEGIN
--SELECT B.NOMBRECOMPLETO RESPONSABLE,F.NOMBRE DESESTADO ,CONVERT(VARCHAR,a.FECHA,103) FECREGISTRO,
--	F.DESCRIPCION COLORESTADO,A.* 
--	FROM SCI_ACCIONES A WITH(NOLOCK)
--	LEFT JOIN  SCI_PERSONA B		WITH(NOLOCK) ON  B.IDPERSONA=A.ID_RESPONSABLE
--	INNER JOIN SCI_TAREAS C			WITH(NOLOCK) ON  C.ID_TAREA=A.ID_TAREA 
--	LEFT JOIN  SCI_MAESTRODETALLE F WITH(NOLOCK) ON  F.CODIGO=A.ESTADO AND F.IDMAESTRO=22
--WHERE 
--		(@IDTAREA = 0 or @IDTAREA is null					or A.ID_TAREA=@IDTAREA)
--	and (@IDACCION = 0 or @IDACCION is null					or A.ID_ACCION=@IDACCION)
--	and	(@IDRESPONSABLE = 0 or @IDRESPONSABLE is null		or A.ID_RESPONSABLE=@IDRESPONSABLE)	
--	and (@ESTADO = 0  or @ESTADO is null					or A.ESTADO=@ESTADO)
--END
--GO




--ALTER PROCEDURE [dbo].[SCI_ListarAlerta] 
--@ID					int =null,
--@IDTAREA		 	int =null,
--@IDRESPONSABLE		int =null,
--@ESTADO				int=null
--AS
--BEGIN

--	SELECT B.NOMBRECOMPLETO SOLICITANTE, C.NOMBRECOMPLETO RESPONSABLE,C.EMAIL,
--	E.NOMBRE TIPOREQUERIMIENTO, F.NOMBRE DESESTADO,F.DESCRIPCION COLORESTADO, H.NOMBRE AREA,CONVERT(VARCHAR,a.FECHAREGISTRO,103) FECREGISTRO,
--	CONVERT(VARCHAR,a.FECHAINIPLAZO,103) FECINIPLAZO, CONVERT(VARCHAR,a.FECHAFINPLAZO,103) FECFINPLAZO ,  I.* 
--	FROM SCI_ALERTAS  I WITH(NOLOCK)  
--	INNER JOIN SCI_TAREAS A WITH(NOLOCK) ON  I.IDRELACIONADO=A.ID_TAREA  AND I.TIPOALERTA=1
--	LEFT JOIN SCI_PERSONA B WITH(NOLOCK) ON  B.IDPERSONA=A.ID_SOLICITANTE
--	LEFT JOIN SCI_MAESTRODETALLE E WITH(NOLOCK) ON  E.CODIGO=A.TIPO AND E.IDMAESTRO=21
--	LEFT JOIN SCI_MAESTRODETALLE F WITH(NOLOCK) ON  F.CODIGO=A.ESTADO AND F.IDMAESTRO=22
--	LEFT JOIN SCI_PERSONA C WITH(NOLOCK) ON  C.IDPERSONA=I.IDPERSONA
--	LEFT JOIN SCI_MAESTRODETALLE H WITH(NOLOCK) ON  H.CODIGO=A.IDAREA AND H.IDMAESTRO=24
--	WHERE  
--		(@IDTAREA = 0	or @IDTAREA is null					or A.ID_TAREA = @IDTAREA )
--	and (@ID = 0		or @ID is null						or I.ID=@ID)
--	and (@IDRESPONSABLE = 0 or @IDRESPONSABLE is null		or A.ID_RESPONSABLE=@IDRESPONSABLE)
--	and (@ESTADO = 0	or @ESTADO is null						or I.ESTADO=@ESTADO)
--END

--GO

