//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDIntegrityEntities : DbContext
    {
        public BDIntegrityEntities()
            : base("name=BDIntegrityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SCI_ACCIONES> SCI_ACCIONES { get; set; }
        public virtual DbSet<SCI_ALERTAS> SCI_ALERTAS { get; set; }
        public virtual DbSet<SCI_CARACTERISTICAS> SCI_CARACTERISTICAS { get; set; }
        public virtual DbSet<SCI_CLASIFICACION> SCI_CLASIFICACION { get; set; }
        public virtual DbSet<SCI_CLIENTEMAST> SCI_CLIENTEMAST { get; set; }
        public virtual DbSet<SCI_COMPANY> SCI_COMPANY { get; set; }
        public virtual DbSet<SCI_COMPROBANTE> SCI_COMPROBANTE { get; set; }
        public virtual DbSet<SCI_COMPROBANTEDETALLE> SCI_COMPROBANTEDETALLE { get; set; }
        public virtual DbSet<SCI_COTIZACION> SCI_COTIZACION { get; set; }
        public virtual DbSet<SCI_COTIZACIONDETALLE> SCI_COTIZACIONDETALLE { get; set; }
        public virtual DbSet<SCI_EMPLEADO> SCI_EMPLEADO { get; set; }
        public virtual DbSet<SCI_GARANTIA> SCI_GARANTIA { get; set; }
        public virtual DbSet<SCI_GARANTIADETALLE> SCI_GARANTIADETALLE { get; set; }
        public virtual DbSet<SCI_LISTABASE> SCI_LISTABASE { get; set; }
        public virtual DbSet<SCI_LISTABASEDETALLE> SCI_LISTABASEDETALLE { get; set; }
        public virtual DbSet<SCI_MAESTRO> SCI_MAESTRO { get; set; }
        public virtual DbSet<SCI_MAESTRODETALLE> SCI_MAESTRODETALLE { get; set; }
        public virtual DbSet<SCI_MARCA> SCI_MARCA { get; set; }
        public virtual DbSet<SCI_MENU> SCI_MENU { get; set; }
        public virtual DbSet<SCI_MENUAUTORIZACION> SCI_MENUAUTORIZACION { get; set; }
        public virtual DbSet<SCI_MENUGRUPO> SCI_MENUGRUPO { get; set; }
        public virtual DbSet<SCI_MODELO> SCI_MODELO { get; set; }
        public virtual DbSet<SCI_NEGOCIO> SCI_NEGOCIO { get; set; }
        public virtual DbSet<SCI_PARAMETROS> SCI_PARAMETROS { get; set; }
        public virtual DbSet<SCI_PERFIL> SCI_PERFIL { get; set; }
        public virtual DbSet<SCI_PERFILUSUARIO> SCI_PERFILUSUARIO { get; set; }
        public virtual DbSet<SCI_PRODUCTO> SCI_PRODUCTO { get; set; }
        public virtual DbSet<SCI_PRODUCTODETALLE> SCI_PRODUCTODETALLE { get; set; }
        public virtual DbSet<SCI_TAREAS> SCI_TAREAS { get; set; }
        public virtual DbSet<SCI_UBIGEO> SCI_UBIGEO { get; set; }
        public virtual DbSet<SCI_USUARIO> SCI_USUARIO { get; set; }
        public virtual DbSet<VIEW_Accesos> VIEW_Accesos { get; set; }
        public virtual DbSet<VIEW_Accion> VIEW_Accion { get; set; }
        public virtual DbSet<VIEW_Alerta> VIEW_Alerta { get; set; }
        public virtual DbSet<VIEW_Garantia> VIEW_Garantia { get; set; }
        public virtual DbSet<VIEW_GarantiaDetalle> VIEW_GarantiaDetalle { get; set; }
        public virtual DbSet<VIEW_Maestro> VIEW_Maestro { get; set; }
        public virtual DbSet<VIEW_Tarea> VIEW_Tarea { get; set; }
        public virtual DbSet<VIEW_TareaAsignadas> VIEW_TareaAsignadas { get; set; }
        public virtual DbSet<VIEW_MaestroDetalle> VIEW_MaestroDetalle { get; set; }
        public virtual DbSet<SCI_PERSONA> SCI_PERSONA { get; set; }
        public virtual DbSet<VIEW_Persona> VIEW_Persona { get; set; }
        public virtual DbSet<SCI_TICKET> SCI_TICKET { get; set; }
        public virtual DbSet<VIEW_Ticket> VIEW_Ticket { get; set; }
    }
}
