//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_LISTABASEDETALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCI_LISTABASEDETALLE()
        {
            this.SCI_COMPROBANTEDETALLE = new HashSet<SCI_COMPROBANTEDETALLE>();
        }
    
        public int IDPRODUCTO { get; set; }
        public int IDLISTABASE { get; set; }
        public Nullable<int> TIPO_COMPONENTE { get; set; }
        public Nullable<decimal> FACTOR { get; set; }
        public Nullable<int> TIPO_FACTOR { get; set; }
        public Nullable<System.DateTime> FEC_INI { get; set; }
        public Nullable<System.DateTime> FEC_FIN { get; set; }
        public Nullable<decimal> PRECIO_BASE { get; set; }
        public Nullable<decimal> PRECIO_LISTA { get; set; }
        public Nullable<decimal> PRECIO_COSTO { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_COMPROBANTEDETALLE> SCI_COMPROBANTEDETALLE { get; set; }
        public virtual SCI_LISTABASE SCI_LISTABASE { get; set; }
        public virtual SCI_PRODUCTO SCI_PRODUCTO { get; set; }
    }
}
