//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCI_PRODUCTO()
        {
            this.SCI_COTIZACIONDETALLE = new HashSet<SCI_COTIZACIONDETALLE>();
            this.SCI_LISTABASEDETALLE = new HashSet<SCI_LISTABASEDETALLE>();
            this.SCI_PRODUCTODETALLE = new HashSet<SCI_PRODUCTODETALLE>();
        }
    
        public int IDPRODUCTO { get; set; }
        public Nullable<int> IDCLASIFICACION { get; set; }
        public Nullable<int> IDMARCA { get; set; }
        public Nullable<int> IDCARACTERISTICA { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DECRIPCION_LARGA { get; set; }
        public string DESCRIPCION { get; set; }
        public string OBSERVACION { get; set; }
        public string MODELO { get; set; }
        public string SECCION { get; set; }
        public string SERIE { get; set; }
        public byte[] MANUAL { get; set; }
        public Nullable<int> TIPOPRODUCTO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<int> INDICADOR_IMPUESTO { get; set; }
        public Nullable<int> IDNEGOCIO { get; set; }
        public string IMAGEN_PRINCIPAL { get; set; }
        public Nullable<int> INDICADOR_B_PRINCIPAL { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIODMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public Nullable<int> IPMODIFICACION { get; set; }
        public Nullable<int> IPCREACION { get; set; }
    
        public virtual SCI_CARACTERISTICAS SCI_CARACTERISTICAS { get; set; }
        public virtual SCI_CLASIFICACION SCI_CLASIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_COTIZACIONDETALLE> SCI_COTIZACIONDETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_LISTABASEDETALLE> SCI_LISTABASEDETALLE { get; set; }
        public virtual SCI_MARCA SCI_MARCA { get; set; }
        public virtual SCI_NEGOCIO SCI_NEGOCIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_PRODUCTODETALLE> SCI_PRODUCTODETALLE { get; set; }
    }
}
