//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_TAREAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCI_TAREAS()
        {
            this.SCI_ACCIONES = new HashSet<SCI_ACCIONES>();
        }
    
        public int ID_TAREA { get; set; }
        public string NROREQUERIMIENTO { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string TAREA { get; set; }
        public Nullable<int> ID_SOLICITANTE { get; set; }
        public Nullable<int> ID_RESPONSABLE { get; set; }
        public Nullable<int> ID_ALTERNO { get; set; }
        public Nullable<int> ID_INVOLUCRADO { get; set; }
        public Nullable<int> IDAREA { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAINIPLAZO { get; set; }
        public Nullable<System.DateTime> FECHAFINPLAZO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_ACCIONES> SCI_ACCIONES { get; set; }
        public virtual SCI_PERSONA SCI_PERSONA { get; set; }
        public virtual SCI_PERSONA SCI_PERSONA1 { get; set; }
        public virtual SCI_PERSONA SCI_PERSONA2 { get; set; }
        public virtual SCI_PERSONA SCI_PERSONA3 { get; set; }
    }
}
