//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_COMPROBANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCI_COMPROBANTE()
        {
            this.SCI_COMPROBANTEDETALLE = new HashSet<SCI_COMPROBANTEDETALLE>();
        }
    
        public int IDCOMPROBANTE { get; set; }
        public Nullable<System.DateTime> FECHAEMISION { get; set; }
        public string NROCOMPROBANTE { get; set; }
        public Nullable<int> TIPOCOMPROBANTE { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string SERIE { get; set; }
        public Nullable<int> TIPOFACTURA { get; set; }
        public Nullable<int> TIPOVENTA { get; set; }
        public Nullable<int> FORMAPAGO { get; set; }
        public string CONCEPTOCOMPROBANTE { get; set; }
        public Nullable<decimal> MONTOAFECTO { get; set; }
        public Nullable<decimal> MONTOIMPUESTO { get; set; }
        public Nullable<decimal> MONTOTOTAL { get; set; }
        public string MONEDA { get; set; }
        public Nullable<int> TIPOCAMBIO { get; set; }
        public Nullable<int> IDNEGOCIO { get; set; }
        public string PERIODO { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<System.DateTime> FECHAVENCIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHACANCELACION { get; set; }
        public Nullable<System.DateTime> FECHAANULACION { get; set; }
        public Nullable<int> IDCOTIZACION { get; set; }
        public string NROCOTIZACION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string IPCREACION { get; set; }
        public string IPMODIFICACION { get; set; }
    
        public virtual SCI_CLIENTEMAST SCI_CLIENTEMAST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_COMPROBANTEDETALLE> SCI_COMPROBANTEDETALLE { get; set; }
        public virtual SCI_COTIZACION SCI_COTIZACION { get; set; }
        public virtual SCI_NEGOCIO SCI_NEGOCIO { get; set; }
    }
}
