//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_ALERTAS
    {
        public int ID { get; set; }
        public int IDRELACIONADO { get; set; }
        public Nullable<int> TIPOALERTA { get; set; }
        public Nullable<int> PROCESO { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> IDPERSONA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUARIOCREACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
    
        public virtual SCI_PERSONA SCI_PERSONA { get; set; }
    }
}
