//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_COMPANY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCI_COMPANY()
        {
            this.SCI_NEGOCIO = new HashSet<SCI_NEGOCIO>();
            this.SCI_PERFILUSUARIO = new HashSet<SCI_PERFILUSUARIO>();
        }
    
        public int IDCOMPANYA { get; set; }
        public string DOCUMENTO { get; set; }
        public string RAZONSOCIAL { get; set; }
        public int IDREPRESENTANTE { get; set; }
        public int IDEMPRESA { get; set; }
        public string URL { get; set; }
        public string DIRECCION { get; set; }
        public string NOMCOMERCIAL { get; set; }
        public string CODIGO { get; set; }
        public string ABREVIATURA { get; set; }
        public string FLATCONEXION { get; set; }
        public string LOGO { get; set; }
        public string LOGOPORTADA { get; set; }
        public string RUTA { get; set; }
        public Nullable<int> IDPERFIL { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string IPCREACION { get; set; }
        public string IPMODIFICACION { get; set; }
    
        public virtual SCI_PERFIL SCI_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_NEGOCIO> SCI_NEGOCIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_PERFILUSUARIO> SCI_PERFILUSUARIO { get; set; }
        public virtual SCI_PERSONA SCI_PERSONA { get; set; }
        public virtual SCI_PERSONA SCI_PERSONA1 { get; set; }
    }
}
