//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCI_PERSONA()
        {
            this.SCI_ALERTAS = new HashSet<SCI_ALERTAS>();
            this.SCI_COMPANY = new HashSet<SCI_COMPANY>();
            this.SCI_COMPANY1 = new HashSet<SCI_COMPANY>();
            this.SCI_GARANTIA = new HashSet<SCI_GARANTIA>();
            this.SCI_GARANTIA1 = new HashSet<SCI_GARANTIA>();
            this.SCI_TAREAS = new HashSet<SCI_TAREAS>();
            this.SCI_TAREAS1 = new HashSet<SCI_TAREAS>();
            this.SCI_TAREAS2 = new HashSet<SCI_TAREAS>();
            this.SCI_TAREAS3 = new HashSet<SCI_TAREAS>();
            this.SCI_TICKET = new HashSet<SCI_TICKET>();
            this.SCI_TICKET1 = new HashSet<SCI_TICKET>();
        }
    
        public int IDPERSONA { get; set; }
        public string DOCUMENTO { get; set; }
        public string RUC { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public string APEPATERNO { get; set; }
        public string APEMATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string PASAPORTE { get; set; }
        public string BREVETE { get; set; }
        public string IDUBIGEO { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string IPCREACION { get; set; }
        public string IPMODIFICACION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string SEXO { get; set; }
        public string ESTADOCIVIL { get; set; }
        public string RUTAFIRMA { get; set; }
        public string TIPOPERSONA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_ALERTAS> SCI_ALERTAS { get; set; }
        public virtual SCI_CLIENTEMAST SCI_CLIENTEMAST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_COMPANY> SCI_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_COMPANY> SCI_COMPANY1 { get; set; }
        public virtual SCI_EMPLEADO SCI_EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_GARANTIA> SCI_GARANTIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_GARANTIA> SCI_GARANTIA1 { get; set; }
        public virtual SCI_UBIGEO SCI_UBIGEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_TAREAS> SCI_TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_TAREAS> SCI_TAREAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_TAREAS> SCI_TAREAS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_TAREAS> SCI_TAREAS3 { get; set; }
        public virtual SCI_USUARIO SCI_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_TICKET> SCI_TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCI_TICKET> SCI_TICKET1 { get; set; }
    }
}
