//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCI_TICKET
    {
        public int IDTICKET { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public Nullable<int> IDSOLICITANTE { get; set; }
        public Nullable<int> IDRESPONSABLE { get; set; }
        public Nullable<System.DateTime> FECHAINI { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string OBSERVACION { get; set; }
        public string SOLUCION { get; set; }
        public string DOCUMENTACION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIODMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string IPMODIFICACION { get; set; }
        public string IPCREACION { get; set; }
    
        public virtual SCI_PERSONA SCI_PERSONA { get; set; }
        public virtual SCI_PERSONA SCI_PERSONA1 { get; set; }
    }
}
