//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_Alerta
    {
        public string SOLICITANTE { get; set; }
        public string RESPONSABLE { get; set; }
        public string EMAIL { get; set; }
        public string TIPOREQUERIMIENTO { get; set; }
        public string DESESTADO { get; set; }
        public string COLORESTADO { get; set; }
        public string AREA { get; set; }
        public string FECREGISTRO { get; set; }
        public string FECINIPLAZO { get; set; }
        public string FECFINPLAZO { get; set; }
        public int ID { get; set; }
        public int IDRELACIONADO { get; set; }
        public Nullable<int> TIPOALERTA { get; set; }
        public Nullable<int> PROCESO { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> IDPERSONA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUARIOCREACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
    }
}
