//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_Persona
    {
        public string DESTIPOPERSONA { get; set; }
        public string DESTIPODOCUMENTO { get; set; }
        public string DESESTADOCIVIL { get; set; }
        public string DESSEXO { get; set; }
        public int IDPERSONA { get; set; }
        public string DOCUMENTO { get; set; }
        public string RUC { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public string APEPATERNO { get; set; }
        public string APEMATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string PASAPORTE { get; set; }
        public string BREVETE { get; set; }
        public string IDUBIGEO { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string IPCREACION { get; set; }
        public string IPMODIFICACION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string SEXO { get; set; }
        public string ESTADOCIVIL { get; set; }
        public string RUTAFIRMA { get; set; }
        public string TIPOPERSONA { get; set; }
        public string DesEstado { get; set; }
        public int Edad { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
    }
}
