//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_Accesos
    {
        public int IDPERSONA { get; set; }
        public string DESTIPOUSUARIO { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public string APEPATERNO { get; set; }
        public string APEMATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string DOCUMENTO { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public string EMAIL { get; set; }
        public int IDUSUARIO { get; set; }
        public Nullable<int> TIPOUSUARIO { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> FLAGEXPIRACION { get; set; }
        public Nullable<System.DateTime> FECHAEXPIRACION { get; set; }
        public string SQLLOGIN { get; set; }
        public string SQLPASSWORD { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> CADUCIDAD { get; set; }
        public string USUARIOCREACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string IPCREACION { get; set; }
        public string IPMODIFICACION { get; set; }
        public string DesEstado { get; set; }
    }
}
